swagger: "2.0"
info:
  title: "Parrot"
  description: >
    Koa Api.
  version: "1.0.0"
host: "localhost:4000/api"
schemes:
  - "http"
paths:
  /health:
    get:
      summary: "Check the status of the service"
      tags:
        - health
      description: "If the service is up and running correctly the response will be 'UP'"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Service is up and healthy"
          schema:
            $ref: "#/definitions/Health"
        500:
          $ref: '#/responses/500'
  /users:
    post:
      tags:
        - users
      summary: "create a user"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        201:
          description: "user created"
          schema:
            $ref: "#/definitions/User"

        204:
          description: "request accepted but don't have user registered"
          schema:
            $ref: "#/definitions/NoContent"

        500:
          $ref: '#/responses/500'
    get:
      summary: "List all users"
      tags:
        - users
      description: "List of users"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "list users"
          schema:
            type: 'array'
            items:
              $ref: "#/definitions/User"

        204:
          description: "request accepted but don't have user registered"
          schema:
            $ref: "#/definitions/NoContent"

        500:
          $ref: '#/responses/500'
  /users/id:
    get:
      summary: "Get a user"
      description: "Get a user"
      tags:
        - users
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Get a user"
          schema:
            $ref: "#/definitions/User"


        204:
          description: "request accepted but don't have user registered"
          schema:
            $ref: "#/definitions/NoContent"

        500:
          $ref: '#/responses/500'
    delete:
      summary: "Delete a user"
      description: "Delete a user"
      tags:
        - users
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Delete a user"
          schema:
            type: 'object'
            properties:
              message:
                type: 'string'

        500:
          $ref: '#/responses/500'
  /users/login:
    post:
      summary: "Login"
      tags:
        - users
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Login user"
          schema:
            type: 'object'
            properties:
              email:
                type: 'string'
                format: 'email'
              password:
                type: 'string'
        500:
          $ref: '#/responses/500'
  /levels:
    get:
      summary: "List levels"
      tags:
        - levels
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Level"
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/Level'
        500:
          $ref: '#/responses/500'
  /promotions:
    get:
      summary: "List promotions"
      tags:
        - promotions
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Promotion"
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/Promotion'
        500:
          $ref: '#/responses/500'
    post:
      tags:
        - promotions
      summary: "create a promotion"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        201:
          schema:
            $ref: "#/definitions/Promotion"

        500:
          $ref: '#/responses/500'
  /promotions/id:
    get:
      summary: "get a promotion"
      tags:
        - promotions
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Promotion"
          schema:
            $ref: "#/definitions/Promotion"

        500:
          $ref: '#/responses/500'
  /benefits:
    get:
      summary: "List benefits"
      tags:
        - benefits
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Benefit"
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/Benefit'
        500:
          $ref: '#/responses/500'
    post:
      tags:
        - benefits
      summary: "create a benefit"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        201:
          schema:
            $ref: "#/definitions/Benefit"

        500:
          $ref: '#/responses/500'
  /benefits/id:
    get:
      summary: "get a benefit"
      tags:
        - benefits
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Benefit"
          schema:
            $ref: "#/definitions/Benefit"

        500:
          $ref: '#/responses/500'

  /documents:
    get:
      summary: "List documents"
      tags:
        - documents
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Document"
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/Document'
        500:
          $ref: '#/responses/500'
    post:
      tags:
        - documents
      summary: "create a document"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        201:
          schema:
            $ref: "#/definitions/Document"

        500:
          $ref: '#/responses/500'
  /documents/id:
    get:
      summary: "get a document"
      tags:
        - documents
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Document"
          schema:
            $ref: "#/definitions/Document"

        500:
          $ref: '#/responses/500'

responses:
  500:
    description: Internal Server Error
    schema:
      $ref: '#/definitions/Error'

definitions:
  Error:
    type: "object"
    properties:
      message:
        type: "string"

  NoContent:
    type: ""

  Health:
    type: "object"
    properties:
      status:
        type: "string"
        enum:
          - "UP"
          - "DOWN"
  User:
    type: "object"
    properties:
      role_id:
        type: 'string'
        format: 'uuid'
      email:
        type: 'string'
        format: 'email'
      password:
        type: 'string'
      name:
        type: 'string'
      level_id:
        type: 'string'
        format: 'uuid'
      birthdate:
        type: 'string'
        format: 'date-time'
      age:
        type: 'number'
      last_vacation:
        type: 'string'
        format: 'date-time'
      last_promotion:
        type: 'string'
        format: 'date-time'
      start_work:
        type: 'string'
        format: 'date-time'
      end_work:
        type: 'string'
        format: 'date-time'
      phone:
        type: 'string'
        format: 'phone'
      emergency_contact:
        type: 'string'
      ahead_card:
        type: 'string'
      current_project:
        type: 'string'
      person_email:
        type: 'string'
        format: 'email'
      fdte_email:
        type: 'string'
        format: 'email'
      bitbucket_account:
        type: 'string'
        format: 'email'
      kids:
        type: 'boolean'
      kids_data:
        type: 'array'
        items:
          type: 'object'
          properties:
            name:
              type: 'string'
            birthdate:
              type: 'string'
              format: 'date-time'

  Level:
    type: 'object'
    properties:
      name:
        type: 'string'
      salary:
        type: 'number'
      benefit_value:
        type: 'number'
  Promotion:
    type: 'object'
    properties:
      person_id:
        type: 'string'
        format: 'uuid'
      level_id:
        type: 'string'
        format: 'uuid'
      date:
        type: 'string'
        format: 'date-time'
      value:
        type: 'number'
      agreement:
        type: 'string'
  Document:
    type: 'object'
    properties:
      person_id:
        type: 'string'
        format: 'uuid'
      type:
        type: 'string'
      number_doc:
        type: 'string'
  Benefit:
    type: 'object'
    properties:
      person_id:
        type: 'string'
        format: 'uuid'
      level_id:
        type: 'string'
        format: 'uuid'
      month_init:
        type: 'string'
        format: 'date-time'
      month_end:
        type: 'string'
        format: 'date-time'
      value:
        type: 'number'
      receipt:
        type: 'string'
      parcel:
        type: 'number'
